tChat: Add missing return on dependency errors
 * The plugin continued to turn on while disabled.
   org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register me.hardstyl3r.tchat.listeners.AsyncChatListener@73734917 while not enabled